### ISSUE TITLE
Working locally, but not on Atmosphere

### ISSUE THREAD

**Issue by jamielob** [okgrow/accounts-ui-react#1]
Looks like `React-Komposer` isn't happy about the load order?

```
W20160819-16:12:31.338(-7)? (STDERR) Error: Cannot find module 'react'
W20160819-16:12:31.338(-7)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20160819-16:12:31.339(-7)? (STDERR)     at Function.Module._load (module.js:276:25)
W20160819-16:12:31.339(-7)? (STDERR)     at Module.require (module.js:353:17)
W20160819-16:12:31.339(-7)? (STDERR)     at require (internal/module.js:12:17)
W20160819-16:12:31.339(-7)? (STDERR)     at Object.<anonymous> (/Users/jamielob/.meteor/packages/okgrow_accounts-ui-react/.0.6.3.1bce9rn++os+web.browser+web.cordova/npm/node_modules/react-komposer/dist/compose.js:33:14)
W20160819-16:12:31.339(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20160819-16:12:31.339(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160819-16:12:31.339(-7)? (STDERR)     at Module.load (module.js:343:32)
W20160819-16:12:31.340(-7)? (STDERR)     at Module.Mp.load (/Users/jamielob/.meteor/packages/babel-compiler/.6.9.1.qlsf2k++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20160819-16:12:31.340(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
```

**Comment by jamielob** [comment]
Fixed by making `react-komposer` a peer dependency.
