### ISSUE TITLE
Does not work with react 16.X

### ISSUE THREAD

**Issue by myrtleTree33** [okgrow/accounts-ui-react#12]
```
W20180422-20:56:36.099(8)? (STDERR) WARNING: npm peer requirements (for thereactivestack:blazetoreact) not installed:
W20180422-20:56:36.100(8)? (STDERR)  - react@16.3.1 installed, react@15.x needed
W20180422-20:56:36.100(8)? (STDERR) 
W20180422-20:56:36.100(8)? (STDERR) Read more about installing npm peer dependencies:
W20180422-20:56:36.100(8)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20180422-20:56:36.100(8)? (STDERR) 
W20180422-20:56:36.107(8)? (STDERR) /home/jhtong/.meteor/packages/meteor-tool/.1.6.1_1.11wyo7i.yctti++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180422-20:56:36.107(8)? (STDERR) 						throw(ex);
W20180422-20:56:36.107(8)? (STDERR) 						^
W20180422-20:56:36.107(8)? (STDERR) 
W20180422-20:56:36.108(8)? (STDERR) TypeError: React.createClass is not a function
W20180422-20:56:36.108(8)? (STDERR)     at BlazeToReact-server.jsx (packages/thereactivestack:blazetoreact/lib/BlazeToReact-server.jsx:6:28)
W20180422-20:56:36.108(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180422-20:56:36.108(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180422-20:56:36.108(8)? (STDERR)     at BlazeToReact.jsx (packages/thereactivestack:blazetoreact/lib/BlazeToReact.jsx:8:18)
W20180422-20:56:36.108(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180422-20:56:36.108(8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180422-20:56:36.108(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/packages/thereactivestack_blazetoreact.js:164:15
W20180422-20:56:36.108(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/packages/thereactivestack_blazetoreact.js:171:3
W20180422-20:56:36.109(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/boot.js:411:36
W20180422-20:56:36.109(8)? (STDERR)     at Array.forEach (<anonymous>)
W20180422-20:56:36.109(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/boot.js:220:19
W20180422-20:56:36.109(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/boot.js:471:5
W20180422-20:56:36.109(8)? (STDERR)     at Function.run (/home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/profile.js:510:12)
W20180422-20:56:36.109(8)? (STDERR)     at /home/jhtong/repos/create4work/app/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
```

**Comment by remingtonchan** [comment]
@myrtleTree33 Hi, have you been able to figure out a workaround? (or even an alternative).

Thank you.

**Comment by derwaldgeist** [comment]
Same issue here. :-/

**Comment by myrtleTree33** [comment]
Hello, what I've done is to downgrade to the version specified in the guide. This works for me.

Latest = cutting edge != stable

**Comment by JarvisXieCA** [comment]
This seems to work: https://github.com/gadicc/meteor-blaze-react-component
